version: '3.1'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: teslodb
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data